FROM junwha/fastvideo

RUN git clone https://github.com/Wan-Video/Wan2.1
RUN cd Wan2.1 && \
    pip install -r requirements.txt

# RUN cd Sparse-VideoGen && \
#     git clone --recursive https://github.com/svg-project/Sparse-VideoGen && \
# #         cd svg/kernels && bash setup.sh
